source "http://rubygems.org"
gem "nokogiri"
gem "rack", "~>1.1"
gem "rspec", :require => "spec"
gem "sinatra"
gem "haml"
gem "ordrin"
gem "rerun"
gem "yelpster"
gem "json"
gem "rest-client"
gem "mailgun"
gem 'activeresource'
